{
 "title": "Arduino Sensors",
 "description": "My Arduino Sensors: temperature, humidity and luminosity",
 "time": { "from": "now", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Arduino Sensors (updated every 2mins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT humidity, temperature, luminosity, created_at FROM arduino_db.sensors ORDER BY created_at "
    }
   ]
  },
  {
   "title": "Current value",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT created_at, humidity, temperature, luminosity FROM arduino_db.sensors ORDER BY created_at DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Humidity (in %)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT humidity FROM arduino_db.sensors ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Humidity (in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT humidity, temperature, luminosity, created_at FROM arduino_db.sensors ORDER BY created_at "
    }
   ]
  },
  {
   "title": "Temperature (-20 to +50 °C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT temperature FROM arduino_db.sensors ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperature (-20 to +50 °C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT humidity, temperature, luminosity, created_at FROM arduino_db.sensors ORDER BY created_at "
    }
   ]
  },
  {
   "title": "Luminosity (0 to 1023)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT luminosity FROM arduino_db.sensors ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Luminosity (0 to 1023)",
   "type": "timeseries",
   "description": "0 = LOW (dark)\n1023 = VERY HIGH (direct sunshine)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "arduino_db",
     "rawSql": "SELECT humidity, temperature, luminosity, created_at FROM arduino_db.sensors ORDER BY created_at "
    }
   ]
  }
 ]
}